# Generated by Django 5.2.17 on 2026-09-01 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_avaliable',
            new_name='is_available',
        ),
    ]
